### ISSUE TITLE
bug(transport) FilesystemTransport - FIFO sort test failed

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#106]
>If FIFO sort does not work on your PR, be sure to have rebased against `main`, if the issue still occurs, consider opening a new PR 🙂

my branch is up to date with upstream, the testTaskListCanBeRetrieved failed.

```bash
1) Tests\SchedulerBundle\Transport\FilesystemTransportTest::testTaskListCanBeRetrieved
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'foo'
+'bar'
```

_Originally posted by @Guikingone in https://github.com/Guikingone/SchedulerBundle/issues/93#issuecomment-835801076_

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Does this issue still relevant in `0.4.9`? Thanks 🙂

**Comment by jvancoillie** [comment]
yes during the last tests this problem still existed. I do not understand why this test passes in the CI and not localy :(

**Comment by jvancoillie** [comment]
Hi @Guikingone 👋  

I just tested again on the main branch and the test still fails.

it looks like this failure is telling the truth 😄 

with the following configuration :
```yaml
scheduler_bundle:
  transport:
    dsn: 'filesystem://first_in_first_out'
  tasks:
    j:
      type: 'null'
    i:
     type: 'null'
    h:
     type: 'null'
    g:
     type: 'null'
    f:
     type: 'null'
    e:
     type: 'null'
    d:
     type: 'null'
    c:
     type: 'null'
    b:
     type: 'null'
    a:
     type: 'null'
```

the tasks are consumed in the following order
```bash
+------+--------------------+------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
| Name | Description        | Expression | Last execution date | Next execution date       | Last execution duration | Last execution memory usage | State   | Tags |
+------+--------------------+------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
| j    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| b    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| a    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| g    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| d    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| f    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| e    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| h    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| c    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| i    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
+------+--------------------+------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
```

but on fifo I expected the following execution

```bash
+------+--------------------+------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
| Name | Description        | Expression | Last execution date | Next execution date       | Last execution duration | Last execution memory usage | State   | Tags |
+------+--------------------+------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
| j    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| i    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| h    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| g    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| f    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| e    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| d    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| c    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| b    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
| a    | No description set | * * * * *  | Not executed        | 2021-05-16T15:41:00+00:00 | Not tracked             | Not tracked                 | enabled |      |
+------+--------------------+------------+---------------------+---------------------------+-------------------------+-----------------------------+---------+------+
```
I looked at what was possible to do with the [finder sort](https://symfony.com/doc/current/components/finder.html#sorting-results) but found nothing conclusive. 

I can't figure out which sort is used by default.

To avoid this incomprehensible order it would be preferable to use a sort either the `sortByName` or `sortByChangeTime`. I am aware that these sorting are not consistent with the FIFO but at least it has the merit of being understandable.

I have doubts about the use of time (change, modify or access) I'm not sure that we have the microseconds to guarantee us a FIFO sorting 😞 

maybe you have other ideas ?

**Comment by Guikingone** [comment]
Hum, strange behaviour, the tests are green and `main` still valid (in the tests I mean). 

I'm starting to think that it could be related to the container "construction phase": https://github.com/Guikingone/SchedulerBundle/blob/d27541c65f5e26f38a6116a37f1e9f0580cd2f37/src/DependencyInjection/SchedulerBundleExtension.php#L811. 

Could you check the `scheduled_at` attribute in the listed tasks? Maybe the container call `schedule` at a certain time and trigger this weird behaviour 🤔

**Comment by jvancoillie** [comment]
all tasks have the same `scheduled_at`
```bash
^ "j"
^ DateTimeImmutable @1621197245 {#814
  date: 2021-05-16 20:34:05.0 +00:00
}
^ "b"
^ DateTimeImmutable @1621197245 {#829
  date: 2021-05-16 20:34:05.0 +00:00
}
^ "a"
^ DateTimeImmutable @1621197245 {#844
  date: 2021-05-16 20:34:05.0 +00:00
  ....
```

even before being sorted by the orchestrator, the finder retrieves the tasks in this order and since they all have the same `scheduled_at` , the sort remains unchanged after FIFO sort.

**Comment by Guikingone** [comment]
Strange situation here, the `scheduled_at` shouldn't be the same for every task (as there's always a small delay) 🤔 

Do you want to work on a fix? 

_PS_: For now, the next release should be `0.5.0`, this one can include bug fixes and new features 🙂

**Comment by jvancoillie** [comment]
Ok it works, i can look at it after work

**Comment by jvancoillie** [comment]
I just took a look.
I think I have identified the problem.

It is located at the task serialization. datetime is normalized with the `RFC3339` format so microseconds are not stored and comparison is done only on seconds.

**Comment by Guikingone** [comment]
Hum, do you have a workaround in mind? 

IMHO, it's not related to `TaskNormalizer` but to `DatetimeNormalizer`, isn't it?

**Comment by jvancoillie** [comment]
Yes that's it, it's the `DatetimeNormalizer` which normalizes by default in `RFC3339` format. 
It is possible to stipulate him the form to use that maybe a solution to be able to normalize the microseconds.

**Comment by Guikingone** [comment]
Re @jvancoillie 👋🏻 

Could you test against `dev-main` if your PR solve the issue, this way we can close this PR 🙂

**Comment by jvancoillie** [comment]
@Guikingone 👋 

it's all right on dev-main. thank you.

If you need any help or need me to test things don't hesitate to ask me it will be with great pleasure.

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Thanks for the feedback, I don't have a lot of issues to give right now (except if you have new features in mind that you may need in the bundle?) but this issue still open: https://github.com/Guikingone/SchedulerBundle/pull/85, any news?
