### ISSUE TITLE
(Documentation): filesystem transport default path

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#124]
In the filesystem transport [documentation](https://github.com/Guikingone/SchedulerBundle/blob/main/doc/transport.md#filesystem) it says that the default path is: `%kernel.project_dir%/var/tasks` or in the FilesystemTransportFactory it is set by default to `sys_get_temp_dir()`

https://github.com/Guikingone/SchedulerBundle/blob/866e6c893cf175b132aa5a412e4394a7d9392835/src/Transport/FilesystemTransportFactory.php#L22

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Hum, I agree, this is strange, do you want to work on a fix? 🤔

**Comment by Guikingone** [comment]
If so, keep in mind that we target `0.5.0` for any fix 🙂

**Comment by jvancoillie** [comment]
I can work on a possible correction, it closely matches the possibility of configuring the default `FlockStore` path https://github.com/Guikingone/SchedulerBundle/pull/102#issuecomment-850866890.

How would you see this default configuration ?

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Small update, there was a bug in the `fs` transport factory, I've pushed a fix that will be released via `0.5.2`, feel free to update when you have time 🙂
