### ISSUE TITLE
bug(worker): lost `isFork` option in ChainedTaskRunner

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#134]
Unless I'm mistaken, when the `Worker` is cloned into the `ChainedTaskRunner` the `isFork` option 
https://github.com/Guikingone/SchedulerBundle/blob/eba50a92cb7f1eb66d03cd8e8524442e974fba1b/src/Worker/AbstractWorker.php#L91
is overwritten at runtime, 
https://github.com/Guikingone/SchedulerBundle/blob/eba50a92cb7f1eb66d03cd8e8524442e974fba1b/src/Runner/ChainedTaskRunner.php#L31-L33
so we are no longer able to determine that this `Worker` is a fork.

---
Another point, how can we from an `WorkerRunningEventListener` of the forked Worker stop the copied Worker (in other words the parent worker in the case of `ChainedTaskRunner`)?

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Nice catch, you're absolutely right, there's an override of the `isFork` option at runtime, I'm gonna fix this issue and the one related to the forked / parent worker, sorry for the issue 🙁

**Comment by Guikingone** [comment]
A fix has been merged in `main` and should be released in `0.5.0`, could you test the issue against `dev-main` when you have a moment? 

Thanks and sorry again for this bug 🙂
