### ISSUE TITLE
bug(command): scheduler:execute shortcut "n" already exists

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#135]
The execution of the command does not work an error is thrown  
```bash
an option with shortcut "n" already exists.
```

this is the default `--no-interaction`shortcut option.

**Comment by Guikingone** [comment]
Hi 👋🏻 

Eurk, nice catch (and an horrible bug), do you want to submit a fix? 😅

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

The bug has been fixed on `main`, must be released in `0.5.0` 🙂
