### ISSUE TITLE
bug(bridge): [MySQL] update() without change throw an exception

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#157]
The `rowCount` on a [MySQL update](https://www.php.net/manual/fr/pdostatement.rowcount.php#104930) without change returns 0 which triggers a false positive on the update.

https://github.com/Guikingone/SchedulerBundle/blob/6dc24eb86ab016d147dbfd1a806a2bd2c71cb143/src/Bridge/Doctrine/Transport/Connection.php#L214

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Sorry for the delay, I'm on holiday and the first week was pretty busy 😄 

Do you want to submit a fix for this issue?

**Comment by jvancoillie** [comment]
I don't mind it but I don't see how to fix it.
Is this check really important?

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

I've pushed a fix via `dev-issue/157`, could you check if it fix the issue when you have a moment? 

Thanks 🙂

**Comment by jvancoillie** [comment]
Hello @Guikingone,

It works 👍
