### ISSUE TITLE
[RFC] Reduce number of matrixes in GA workflows

### ISSUE THREAD

**Issue by jmsche** [Guikingone/SchedulerBundle#209]
Hi,

What about reducing matrixes in workflows?

For example I don't see the point of running PHP CS Fixer on both Ubuntu & macOS, on both PHP 7.4 & PHP 8.0.

It would increase readability of checks when submitting a PR.

**Comment by jmsche** [comment]
Proposal:

* PHPUnit:
    * Drop "composer-dependencies" from matrix?
    * Symfony versions will be handled via #207 
    * PHP: all supported
    * OS: Ubuntu only (it's already the case)
* Other workflows:
    * PHP: highest supported (currently 8.0, would be 8.1 soon) only
    * Deps: default (highest I guess) only
    * OS: Ubuntu only

That would considerably reduce the number of checks: for my current #207 PR, it would go from 48 checks to 10 if my calculations are right :)

**Comment by Guikingone** [comment]
Hi 👋🏻 

Sorry, didn't get the notice for these issue 🙁 

> Drop "composer-dependencies" from matrix?

Hum, what's the point here? Testing ONLY against highest? 

> Symfony versions will be handled via Allow Symfony 6 #207

Currently #31 add support for Sf 6 & PHP 8.1

> OS: Ubuntu only (it's already the case)

Why not testing it against macOS? 

> PHP: highest supported (currently 8.0, would be 8.1 soon) only

So, you want to remove 7.4 support?

**Comment by jmsche** [comment]
> Hum, what's the point here? Testing ONLY against highest?

As tests can be configured on several Symfony versions, "lowest" would be eg. Symfony 5.4.*? 

> Why not testing it against macOS?

Code is supposed to be okay on all OS, if not then I think it's either an OS issue, or a PHP issue, but that should not be relevant on the bundle. But I may be wrong :)

> So, you want to remove 7.4 support?

Well, yes, as it does not get active support anymore, only security issues: https://www.php.net/supported-versions

**Comment by Guikingone** [comment]
> Well, yes, as it does not get active support anymore, only security issues: https://www.php.net/supported-versions

Well, if it was only a personal decision, I'd removed 7.4 support a long time ago but it seems that the bundle is highly used with 7.4: 

![Screenshot 2021-11-30 at 08 59 42](https://user-images.githubusercontent.com/13744329/144008172-633a4060-d3d9-4b00-81fb-7efde61bf9ad.png)

> Code is supposed to be okay on all OS, if not then I think it's either an OS issue, or a PHP issue, but that should not be relevant on the bundle. But I may be wrong :)

You're right on this point, macOS can be safely removed, Linux should be enough.

> As tests can be configured on several Symfony versions, "lowest" would be eg. Symfony 5.4.*?

Lowest IS 5.4 where highest either can be relevant to Doctrine and Sf 🤔

**Comment by Guikingone** [comment]
Hi @jmsche 👋🏻 

Small update about yesterday discussion: 

- Regarding PHP, `7.4` support will be dropped, `8.0` becoming the de facto version to use.
- Regarding Symfony, `5.2` support will be dropped, `5.4` becoming the de facto version to use along with `6.0`.

**Comment by jmsche** [comment]
Hi @Guikingone,

Here I am, coming again with this issue :D

Here is a new proposal (as some recent PRs have improved things like #269):

* Code style: run against PHP 8.1 (latest) only, with highest dependencies only?
* Docker: drop macOS-latest?
* Infection: run against PHP 8.1 (latest) only, with highest dependencies only?
* PHPUnit: keep as it is
* Rector: run against PHP 8.1 (latest) only, with highest dependencies only?
* Security: keep as it is
* Static analysis: run against PHP 8.1 (latest) only, with highest dependencies only?

So the main changes would be:

* run Code style/Infection/Rector/Static analysis only with PHP 8.1 (current latest) & highest dependencies
* dropping macOS-latest for Docker (not sure if it would matter or not)

WDYT?

**Comment by jmsche** [comment]
Closing as #271 was merged 🎉
