### ISSUE TITLE
Segmentation fault with the 0.9.0 tag 

### ISSUE THREAD

**Issue by xaviermarchegay** [Guikingone/SchedulerBundle#241]
PHP 8.1, opcache disabled (usually enabled bu disabled to debug the issue)

> php -dmemory_limit=-1 bin/console 
> Symfony 6.0.7 (env: dev, debug: true) #StandWithUkraine https://sf.to/ukraine
> 
> Usage:
>   command [options] [arguments]
> 
> Options:
>   -h, --help            Display help for the given command. When no command is given display help for the list command
>   -q, --quiet           Do not output any message
>   -V, --version         Display this application version
>       --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
>   -n, --no-interaction  Do not ask any interactive question
>   -e, --env=ENV         The Environment name. [default: "dev"]
>       --no-debug        Switch off debug mode.
>   -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
> 
> **Segmentation fault (core dumped)**

If I don't specify the memory_limit, it crashed with

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/vendor/symfony/dependency-injection/Argument/RewindableGenerator.php on line 32

The only change is the 0.9 version.

@Guikingone I don't know how to debug the segmentation faults, can you help me?

**Comment by Guikingone** [comment]
Hi @xaviermarchegay 👋🏻 

Seems strange, I see that you're doing a `php -dmemory_limit=-1 bin/console`, have you cleaned the cache?

**Comment by xaviermarchegay** [comment]
@Guikingone Yes, same output with rm -rf var/cache/* && php -dmemory_limit=-1 bin/console

**Comment by Guikingone** [comment]
Hum ... Strange, I'm facing the same error locally 🤔

**Comment by Guikingone** [comment]
Ok, fast investigation, it seems that the `transport` is created in a loop (don't know why at the moment), could you rollback temporarily to `0.8`?

Sorry 😅

**Comment by xaviermarchegay** [comment]
@Guikingone No problem, I did not really need the 0.9.0 tag right now anyway. Take your time.

**Comment by Guikingone** [comment]
Ok, back with a fix 😄 

Could you see if `dev-fix/memory_limit` fix it? It works locally but I don't trust my local build anymore 😄

**Comment by xaviermarchegay** [comment]
@Guikingone Perfect, no error anymore

**Comment by Guikingone** [comment]
Hi @xaviermarchegay 👋🏻 

Fix released via `0.9.1`, have a great day 🙂
