### ISSUE TITLE
Doctrine and Redis transport factories are not injected into TransportFactory constructor

### ISSUE THREAD

**Issue by MarcelWilhelmi** [Guikingone/SchedulerBundle#35]
Hello,

now with the new version 0.3.2 I'm trying to use the doctrine transport, but somehow the DoctrineTransportFactory and RedisTransportFactory implementations of the interface TransportFactoryInterface are not being injected into the TransportFactory constructor and so the error message I get is `No transport supports the given Scheduler DSN "doctrine://..."`

All implementations under /src/Transport are injected by the DI system, but the two lying under /src/Bridge/... are not.
Is this a configuration issue on my side?

Kind regards,
Marcel

**Comment by Guikingone** [comment]
Hi @MarcelWilhelmi 

Hum, strange behaviour here as both factories are tagged: 

```php
        $container->register(DoctrineTransportFactory::class, DoctrineTransportFactory::class)
            ->setArguments([
                new Reference('doctrine', ContainerInterface::EXCEPTION_ON_INVALID_REFERENCE),
            ])
            ->setPublic(false)
            ->addTag('scheduler.transport_factory')
            ->addTag('container.preload', [
                'class' => DoctrineTransportFactory::class,
            ])
        ;
// ...

        $container->register(RedisTransportFactory::class, RedisTransportFactory::class)
            ->setPublic(false)
            ->addTag('scheduler.transport_factory')
            ->addTag('container.preload', [
                'class' => RedisTransportFactory::class,
            ])
        ;
```

The only reason that I can see is that `doctrine` is not available: 

```php
if (!$container->hasDefinition('doctrine')) {
       return;
}
```

Does `doctrine` service available in your application? 🤔

**Comment by Guikingone** [comment]
Ok, small update, it seems that the factory is registered but only if the definition for `doctrine` is available, thing is, at the compile time, the definition is not set, i'm working on a fix, keep you updated 🙂

**Comment by MarcelWilhelmi** [comment]
Thanks for the quick fix :-)
