### ISSUE TITLE
DoctrineTransport table_name configuration

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#41]
The configuration of the table name (table_name) for the Doctrine transport as described in the document does not work, a camelCase notation is expected in the DoctrineTransportFactory [L39](https://github.com/Guikingone/SchedulerBundle/blob/bbcf1eb58a86dbefde4eb04f166dcc4fa150d87f/src/Bridge/Doctrine/Transport/DoctrineTransportFactory.php#L39) 
by modifying the option in camelCase notation the name of the table is taken into account.

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Wow, nice catch, seems to be related (as looked in the changelog) to a recent refactoring, do you want to create a PR to fix it or do you prefer to me to handle the fix? 🙂

**Comment by jvancoillie** [comment]
no problem, I should be able to offer a pull request.
To keep the snake_case notation consistent, I will change the tableName option to table_name in the DoctrineTransportFactory.

**Comment by Guikingone** [comment]
@jvancoillie I agree on the change, don't forget (if you have time) to add a regression test on the value passed in the option 🙂
