### ISSUE TITLE
bug ( Notice: Undefined index: transport ) - configuring guikingone/scheduler-bundle

### ISSUE THREAD

**Issue by MedMed59** [Guikingone/SchedulerBundle#56]
Hello,

I have a little problem during the installation of the bundle. 
I get an error in 

```
Using version ^0.4.0 for guikingone/scheduler-bundle
./composer.json has been updated
Running composer update guikingone/scheduler-bundle
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking dragonmantank/cron-expression (v3.1.0)
  - Locking guikingone/scheduler-bundle (0.4.0)
  - Locking symfony/lock (v5.2.6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing symfony/lock (v5.2.6): Extracting archive
  - Installing dragonmantank/cron-expression (v3.1.0): Extracting archive
  - Installing guikingone/scheduler-bundle (0.4.0): Extracting archive
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
101 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Endroid Installer detected project type "symfony"

Symfony operations: 2 recipes (ddf663939bb7c4e416e77206b09ab2a6)
  - Configuring symfony/lock (>=5.2): From github.com/symfony/recipes:master
  - Configuring guikingone/scheduler-bundle (>=0.4.0): From auto-generated recipe
Synchronizing package.json with PHP packages
Don't forget to run npm install --force or yarn install --force to refresh your JavaScript dependencies!
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In SchedulerBundleExtension.php line 228:
!!                                        
!!    Notice: Undefined index: transport  
!!                                        
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Where does this problem come from?

**Comment by Guikingone** [comment]
Hi @MedMed59 👋🏻 

Strange issue, can you give me more details, have you any configuration already defined before installing it?

**Comment by MedMed59** [comment]
Of course, my symfony version is **5.2.6**, I already had a configuration before installing it
Do you want me to give you my composer.json or other config file?

**Comment by Guikingone** [comment]
Just the `scheduler.yaml` file if you have one 🙂

**Comment by MedMed59** [comment]
The file `scheduler.yaml` was not generated

**Comment by Guikingone** [comment]
Hum strange, so you don't have any previous installation of the bundle. 

The only relation here can be the introduction of the cache transport (which requires the `transport` key), I'm gonna investigate the issue.

**Comment by Guikingone** [comment]
Hi @MedMed59 👋🏻 

Small follow-up, can you try installing it using the `dev-fix/dic_extension` branch? I've tested on a local project and it seems to work but as you have your own project, it could be a good way to validate it 🙂 

Thanks.

**Comment by MedMed59** [comment]
Hi @Guikingone ,
I just tested using the "dev-fix/dic_extension" branch but I still have the same error

```

Symfony operations: 2 recipes (65d0b7c021116b3e21a77017c1fa64c5)
  - Configuring symfony/lock (>=5.2): From github.com/symfony/recipes:master
  - Configuring guikingone/scheduler-bundle (>=dev-fix/dic_extension): From auto-generated recipe
Synchronizing package.json with PHP packages
Don't forget to run npm install --force or yarn install --force to refresh your JavaScript dependencies!
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In SchedulerBundleExtension.php line 257:
!!                                        
!!    Notice: Undefined index: transport  
!!                                        
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

**Comment by Guikingone** [comment]
Hum, strange, I'm gonna continue to investigate it 🤔

**Comment by Guikingone** [comment]
Ok, small follow-up, I've pushed a fix on the same branch as yesterday, I've tested it on a fresh project and it seems to solve the issue, can you confirm? 

If yes, the patch will be released as `0.4.1` once the CI is green 🙂

**Comment by MedMed59** [comment]
Yes, it's good ! I had no problem installing :)

**Comment by Guikingone** [comment]
The bundle can be installed without creating the configuration file, thanks to the fix, the services will not be injected into the container, once a configuration file is defined, the services are injected thanks to the configuration. 

As the bundle is not a `recipe` (for now), the configuration file is not created 🙂

**Comment by Guikingone** [comment]
`0.4.1` will be released once the `main` CI is green, thanks for the patience and sorry for this issue 🙂

**Comment by Guikingone** [comment]
UPDATE: `0.4.1` released 🚀
