### ISSUE TITLE
Unable to create a MessengerTask

### ISSUE THREAD

**Issue by babeuloula** [Guikingone/SchedulerBundle#63]
Hello,

I want to create a MessengerTask in order to create task and register it on your scheduler, and your scheduler tell to messenger "disptach this message".

```php
$task = (new MessengerTask(uniqid(), new FooSchedulerMessage("My message")))
	->setExpression(
		$fluentExpression
			->build($expression, 'Europe/Paris')
			->getExpression()
	)
	->setTimezone(new \DateTimeZone('Europe/Paris'))
	->setSingleRun(true)
;
$scheduler->schedule($task);
```

```yaml
scheduler_bundle:
    transport:
        dsn: 'doctrine://default?execution_mode=first_in_first_out&table_name=scheduler_tasks'
```

With this code I've got an error : 

```
Argument 2 passed to SchedulerBundle\Serializer\TaskNormalizer::SchedulerBundle\Serializer\{closure}() must be an instance of SchedulerBundle\Task\MessengerTask, instance of App\Message\FooSchedulerMessage given, called in /var/www/html/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php on line 188
```

My stack: 
- Symfony: 5.2.2
- PHP FPM: 7.4
- Scheduler Bundle: 0.4.1
- Symfony Messenger: 5.2.5

----

The crash is located here : 

https://github.com/Guikingone/SchedulerBundle/blob/d5756a074a80029f2901b1405b776462859c64ac/src/Serializer/TaskNormalizer.php#L120-L123

You test a serializer but it's not a normalizer instead ?

https://github.com/Guikingone/SchedulerBundle/blob/d5756a074a80029f2901b1405b776462859c64ac/tests/Serializer/TaskNormalizerTest.php#L413-L428

Thanks

**Comment by Guikingone** [comment]
Hi @babeuloula 👋🏻 

Strange behaviour here, I've tried to reproduce the bug locally in the tests, I don't find a way 🤔 

Regarding the following comment: 

> You test a serializer but it's not a normalizer instead ?

The test is written around the serializer as we need a serializer to use `ObjectNormalizer`, here's a test that tries to reproduce the context: 

```php
public function testMessengerTaskCanBeNormalized(): void
    {
        $objectNormalizer = new ObjectNormalizer(null, null, null, new PropertyInfoExtractor([], [new PhpDocExtractor(), new ReflectionExtractor()]));
        $notificationTaskBagNormalizer = new NotificationTaskBagNormalizer($objectNormalizer);

        $normalizer = new TaskNormalizer(
            new DateTimeNormalizer(),
            new DateTimeZoneNormalizer(),
            new DateIntervalNormalizer(),
            $objectNormalizer,
            $notificationTaskBagNormalizer
        );

        $serializer = new Serializer([
            $notificationTaskBagNormalizer,
            $normalizer,
            new DateTimeNormalizer(),
            new DateIntervalNormalizer(),
            new JsonSerializableNormalizer(),
            $objectNormalizer
        ], [new JsonEncoder()]);
        $objectNormalizer->setSerializer($serializer);

        $task = (new MessengerTask(uniqid(), new FooMessage()))
            ->setExpression('* * * * *')
            ->setTimezone(new DateTimeZone('Europe/Paris'))
            ->setSingleRun(true)
        ;

        $data = $normalizer->normalize($task, 'json');

        self::assertArrayHasKey('taskInternalType', $data);
        self::assertSame(MessengerTask::class, $data['taskInternalType']);
        self::assertArrayHasKey('body', $data);
        self::assertArrayHasKey('message', $data['body']);
        self::assertArrayHasKey('class', $data['body']['message']);
        self::assertArrayHasKey('payload', $data['body']['message']);
    }
```

The test is valid, maybe I miss something? 🤔 

PS: Here's the related PR: https://github.com/Guikingone/SchedulerBundle/pull/66

**Comment by babeuloula** [comment]
Hello,

🤔 Monday I will try to reproduice and I will send you a public repo with the bug.

**Comment by babeuloula** [comment]
Hello @Guikingone, you can clone [this repo](https://github.com/babeuloula/guikingone-scheduler-bundle-messenger-task) and test it.

If you have an error with mkcert, just comment [this line](https://github.com/babeuloula/guikingone-scheduler-bundle-messenger-task/blob/master/docker/install.sh#L17) and use 8888 instead of 80.

**Comment by Guikingone** [comment]
Hi @babeuloula 👋🏻 

I'm gonna take time to investigate this bug, it should be merged for `0.4.3` 🙂

**Comment by Guikingone** [comment]
Hi @babeuloula 👋🏻 

I'm seeing that you're using `0.4.1`, could you update your dependencies to `0.4.2` and test again the process ? 🤔 

I've tested locally and via the repository, both succeed 🙁

**Comment by babeuloula** [comment]
Hello @Guikingone,

I don't know why and how but I've restart a new project with the same dependencies and I've no longer this issue. It's very weird ...

If you can't reproduice this bug (and now me) I can't explain where the problem come from.

Thanks for your time.
You can close this issue if you want.

**Comment by Guikingone** [comment]
Hi @babeuloula 👋🏻 

Strange situation, I'm gonna keep an eye on this issues and add more tests to confirm that every task type can be used in `Doctrine` bridge avec with `Messenger` integration, I'm closing this PR but working on background on this use case. 

Thanks again for the feedback 🙂
