### ISSUE TITLE
refactor(worker): sub-tasks output

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#77]
it is not possible to have the output for "sub-tasks" in chained tasks type, are there any plans to improve this ?

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

That's a current limitation on `ChainedTask` as the events are triggered only for the "master" task and not for each embedded task, that's something I want to to improve, if you want to work on it, feel free to open a PR 🙂

**Comment by jvancoillie** [comment]
just try to recurse execution on ChainTask and it display output :) 

with this following condition at L118 in the Worker 

```php
if($task instanceof ChainedTask){
    $this->execute($options, ...$task->getTasks());
}
```

https://github.com/Guikingone/SchedulerBundle/blob/0efd88bdd39c04dda6f9f821465f70f1305ea15a/src/Worker/Worker.php#L115-L125



I don't know if this has any side effects

**Comment by jvancoillie** [comment]
by processing the sub-tasks of a chainedType with the execute method of the worker it allows to keep all the logic of task processing (failedTasks, output, Events, ...)

**Comment by Guikingone** [comment]
The main issue is the usage of runners, by adding this method, the `ChainedTaskRunner` still used and will execute the embedded tasks twice.

**Comment by jvancoillie** [comment]
yes I noticed that :(, I thought it was an interesting idea.

**Comment by Guikingone** [comment]
The idea is interesting, I'm not saying that its not 😄 

I'm just not sure about the implementation 🤔

**Comment by jvancoillie** [comment]
Better implementation so 😄 

```php
interface RunnerInterface
{
    public function run(TaskInterface $task, WorkerInterface $worker): Output;

    public function support(TaskInterface $task): bool;
}
```

```php
final class ChainedTaskRunner implements RunnerInterface
{

    /**
     * {@inheritdoc}
     */
    public function run(TaskInterface $task, WorkerInterface $worker): Output
    {
        if (!$task instanceof ChainedTask) {
            $task->setExecutionState(TaskInterface::ERRORED);
            return new Output($task, null, Output::ERROR);
        }

        try {
           $worker->execute($worker->getOptions(), ...$task->getTasks());
        } catch (Throwable $throwable) {
            $task->setExecutionState(TaskInterface::ERRORED);
            return new Output($task, $throwable->getMessage(), Output::ERROR);
        }

        $task->setExecutionState(TaskInterface::SUCCEED);
        return new Output($task, null, Output::SUCCESS);
    }
}
```

**Comment by Guikingone** [comment]
I kinda like this one BUT, have you tested it locally? 

I'm not sure about the worker injection in the runners during runtime, this could lead to memory limit or circular "leak" where the worker will continue to execute and execute tasks 🤔

**Comment by Guikingone** [comment]
Hi @jvancoillie 

The improvement will be merged for `0.5.0`, could you test it against `dev-main` when you have a moment? 

Thanks 🙂

**Comment by jvancoillie** [comment]
@Guikingone 👋 

Great news,i will have a look at this;

**Comment by jvancoillie** [comment]
I just took a quick look at it. there are things that strike me as weird. I will go into that further tomorrow.
